### PR TITLE
OBSOLETE: Add build step to optionally install/configure xdebug

### PR DESCRIPTION
**Pull request by fuhbar**

### CODE REVIEW

**Comment by tonyfahrion** [comment]
What about always compiling xdebug and only activating it if `$ENABLE_XDEBUG` is set? So our users are able to enable xdebug on-demand.

**Comment by fuhbar** [comment]
Good idea. Actually this is something I am currently implementing for conditional opcache employment.

**Comment by tonyfahrion** [comment]
I added a version pinning for pecl extensions (via `defaults.inc.sh` so we can make sure, that a build works. For xdebug the current version would be `2.5.4`.

What is your opinion here, should we pin versions (which would require us to maintain updates by ourselfs), or should we always use `latest` (which might fail compilation / break spryker code)?

**Comment by fuhbar** [comment]
AFAIK the pecl versions to be installed are not dependant on the version of the current PHP runtime environment, right? 

If so I would opt for pinned versions in favor of reproducible builds, even if its more knobs to keep track and fiddle around with.

**Comment by tonyfahrion** [comment]
> AFAIK the pecl versions to be installed are not dependant on the version of the current PHP runtime environment, right?

Pecl extensions are getting compiled against the PHP source - so they are depending at least on the internal PHP API.
I opt for pinned versions too :)

**Comment by fuhbar** [comment]
Pinning implemented in 504ea88

**Pull request closed without merging**
